version: "3.9"
services:
  backend:
    build: ./backend
    container_name: node-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  mongo_data:
